name: 'adwords'
version: '0.3.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
seed-paths: ["data"]

vars:
  etl:                            #stitch or fivetran
  criteria_performance_report:    #"schema.table"
  click_performance_report:       #"schema.table"
  final_url_performance_report:   #"schema.table"
  ads_table:                      #"schema.table" (only for stitch)
  ad_groups_table:                #"schema.table" (only for stitch)
  accounts_table:                 #"schema.table" (only for stitch)
  campaigns_table:                #"schema.table" (only for stitch)
  adapter_value:                  #url or criteria

      
